# arena related definitions
arena:
  host: arenaxr.org # default: arenaxr.org
  realm: realm # default: realm
  scenename: questions-example # one of the scenes defined below

# where the icon files are
badge_icons:
  question: https://arenaxr.org/store/users/wiselab/questions/img/question.png
role_icons:
  question: https://arenaxr.org/store/users/wiselab/questions/img/question.png

# icon placement relative to avatar
badge:
  position: 0, -2, 0
  rotation: 0, 0, 0, 1
  img_height: 2
  max_icons: 10
role:
  position: 0, 2, 0
  rotation: 0, 0, 0, 1
  img_height: 2
  max_icons: 1
